name: Run tests
on: [push]
jobs: 
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
          - run: echo Testing, testing, beep boop baap....
          - run: cd js
          - run: npm install
          - run: npm run test